# Generated by Django 4.1.6 on 2023-02-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_carshop_options_carshop_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='amout_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of products'),
            preserve_default=False,
        ),
    ]
