# Generated by Django 4.1.6 on 2023-02-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='offer price'),
        ),
    ]
