# Generated by Django 4.1.6 on 2023-02-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False, verbose_name='Is offer?'),
        ),
    ]
