# Generated by Django 4.1.6 on 2023-02-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_register',
            field=models.CharField(blank=True, max_length=6, verbose_name='Register code'),
        ),
    ]
