# Generated by Django 4.1.6 on 2023-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ocupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(choices=[('0', 'Administrator'), ('1', 'Worker'), ('2', 'Client')], default='2', max_length=1),
        ),
    ]
