# Generated by Django 4.1.6 on 2023-02-22 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(verbose_name='Sale date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('0', 'Credit card'), ('1', 'Cash'), ('2', 'Other')], max_length=1, verbose_name='Payment type')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total revenue')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='DetailsSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price sale')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Purchase price')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Revenue')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sale', to='sales.sale', verbose_name='Code sale')),
            ],
            options={
                'verbose_name': 'Sale detail',
                'verbose_name_plural': 'Sale details',
            },
        ),
    ]
