# Generated by Django 4.1.6 on 2023-03-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_detailssale_created_detailssale_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
    ]
