# Generated by Django 4.1.6 on 2023-03-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_offer_price'),
        ('sales', '0004_remove_sale_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailssale',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_sale', to='products.product', verbose_name='product'),
        ),
    ]
